[env:esp32dev]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.variant = esp32
build_flags =
  -D CORE_DEBUG_LEVEL=1
lib_deps =
  miguelbalboa/MFRC522
  bblanchon/ArduinoJson@^7.1.0
